# Generated by Django 5.1.5 on 2025-04-23 11:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodlog',
            options={'ordering': ['-date'], 'verbose_name': 'Mood Log', 'verbose_name_plural': 'Mood Logs'},
        ),
        migrations.AlterModelOptions(
            name='phq9response',
            options={'ordering': ['-date'], 'verbose_name': 'PHQ-9 Response', 'verbose_name_plural': 'PHQ-9 Responses'},
        ),
        migrations.AddField(
            model_name='phq9response',
            name='responses',
            field=models.JSONField(default=dict, help_text='Dictionary of question-answer pairs'),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='mood',
            field=models.PositiveSmallIntegerField(help_text='1-10 scale (1=Worst, 10=Best)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phq9response',
            name='score',
            field=models.PositiveSmallIntegerField(help_text='PHQ-9 total score (0-27)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(27)]),
        ),
        migrations.AlterField(
            model_name='phq9response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phq9_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
