# Generated by Django 5.1.5 on 2025-03-02 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_patient_and_more'),
        ('users', '0011_alter_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistavailability',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='users.therapist'),
        ),
    ]
