# Generated by Django 5.1.5 on 2025-03-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_therapistavailability_therapist'),
        ('users', '0011_alter_profile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistavailability',
            name='day',
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='available_days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.therapist'),
        ),
    ]
