# Generated by Django 5.1.5 on 2025-03-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_therapistavailability_available_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistavailability',
            name='available_days',
            field=models.JSONField(default=list),
        ),
    ]
