# Generated by Django 5.1.5 on 2025-03-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_remove_appointment_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistavailability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
