# Generated by Django 5.1.5 on 2025-03-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_therapistavailability_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
