# Generated by Django 5.1.5 on 2025-04-10 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_appointment_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Reschedule', 'Reschedule'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('No Show', 'No Show')], default='Pending', max_length=20),
        ),
    ]
