# Generated by Django 5.1.5 on 2025-02-25 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_concerns_profile_preferred_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtherapist',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_specialist', to=settings.AUTH_USER_MODEL),
        ),
    ]
