# Generated by Django 5.1.5 on 2025-02-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_assignedtherapist_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='concerns',
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
