# Generated by Django 5.1.5 on 2025-02-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_concerns_profile_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preferred_language',
            new_name='language',
        ),
    ]
