# Generated by Django 5.1.5 on 2025-02-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_preferred_language_profile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='specialization',
        ),
        migrations.AddField(
            model_name='profile',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='users.specialization'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='specializations',
            field=models.ManyToManyField(to='users.specialization'),
        ),
    ]
