# Generated by Django 5.1.5 on 2025-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_specialization_remove_profile_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Swahili', 'Swahili'), ('English, Swahili', 'English, Swahili')], max_length=50, null=True),
        ),
    ]
