# Generated by Django 5.1.5 on 2025-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='profile_files/'),
        ),
    ]
