# Generated by Django 5.1.5 on 2025-04-01 18:25

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Number of years of professional experience'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='license_number',
            field=models.CharField(blank=True, help_text='Professional license/certification number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='profile_picture',
            field=models.ImageField(blank=True, default='therapist_profile_pics/default.jpg', null=True, upload_to='therapist_profile_pics/'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='qualifications',
            field=models.TextField(blank=True, default='', help_text='List your professional degrees, certifications, and qualifications', null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='verified',
            field=models.BooleanField(default=False, help_text='Designates whether this therapist has been verified by admin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), users.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='profile_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt']), users.models.validate_uploaded_file_size]),
        ),
    ]
