# Generated by Django 5.1.5 on 2025-04-02 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_therapist_bio_therapist_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='specialization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='therapist_profile_pics/'),
        ),
    ]
