# Generated by Django 5.1.5 on 2025-03-19 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='resource',
            name='categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
